### Data Structure 1/06/2024

#### Lists 

##### Dictionaries 

##### What is List ?
 Lists are data structures that contain an ordered collection of elements.

##### Why do we use Lists?
Lists are commonly used in programming to store and orgainse data so it can be easily stored, indexed or searched.

### Creating a List

In [3]:
list_1=[3,6,19]
print(list_1)

[3, 6, 19]


### Adding an item to a List 

In [4]:
list_1.append(25)
print(list_1)

[3, 6, 19, 25]


### Changing an item in a List 

In [6]:
list_1[1]=12
print(list_1)

[3, 12, 19, 25]


on the above code if used curvy brakets you will get an error - just try 
list_1(1)=12
print(list_1)
try 

### Storing different data type in a List

In [7]:
list_2=["Arya",39,2024,4.9]
print(list_2)

['Arya', 39, 2024, 4.9]


### Removing an item from a List 

In [8]:
list_2.remove(39)
print(list_2)

['Arya', 2024, 4.9]


In [10]:
list_2.pop(2)
print(list_2)

['Arya', 2024]


### Merging two Lists

In [11]:
list_1.append(list_2)
print(list_1)

[3, 12, 19, 25, ['Arya', 2024]]


### Accessing items in a List

In [13]:
list_1[0]

3

In [14]:
list_1[0:3]

[3, 12, 19]

In [15]:
list_1[:3]

[3, 12, 19]

In [16]:
list_1[1:]

[12, 19, 25, ['Arya', 2024]]

In [17]:
list_1[4]

['Arya', 2024]

In [18]:
range(0,10)

range(0, 10)

In [20]:
for i in range(11):
    print(i)

0
1
2
3
4
5
6
7
8
9
10


In [23]:
list_1=[3,6,19]

In [30]:
for i in [list_1]:
    print(i)

[3, 6, 19]


In [32]:
list_3=[i*i for i in list_1]
print(list_3)

[9, 36, 361]


### Another way of creating a list 

In [33]:
list_4=list()
print(list_4)

[]


In [34]:
for i in (list_1):
    print(i*i)

9
36
361


In [37]:
for i in list_1:
    list_4.append(i*i)
list_4

[9, 36, 361, 9, 36, 361, 9, 36, 361]

### Check if key exixts in a List

In [61]:
if 36 in list_4:
    print("yes")

yes


### Dictionaries 

#### What is a Dictionary ?
Dictionaries are data structures that contain a collection of "key" and "value" pairs where each key reads to be unique string and the value can range from a single variable, to other data structures (such as another dictionary, or a list).

### Creating a Dictionary 
There are two ways to create an empty dictionary my_dict() or my_dict={}. The following example illustrates how to create a dictionary with keys and values..

In [38]:
dict_1={'protein_A':174,
       'protein_B':226}

In [39]:
dict_1

{'protein_A': 174, 'protein_B': 226}

In [40]:
dict_2=dict(protein_A=174, protein_B=226)

In [41]:
dict_2

{'protein_A': 174, 'protein_B': 226}

### Adding items to adictionary 

In [42]:
dict_1['protein_c']=556

In [43]:
dict_1

{'protein_A': 174, 'protein_B': 226, 'protein_c': 556}

In [44]:
dict_1['protein_c']

556

### Removing items from a Dictionary

In [45]:
dict_1.pop('protein_c')

556

In [46]:
dict_1

{'protein_A': 174, 'protein_B': 226}

### Accessing items in a Dictionary

In [47]:
dict_1['protein_A']

174

In [48]:
dict_1.get('protein_A')

174

In [49]:
dict_1.values()

dict_values([174, 226])

In [50]:
dict_1.copy()

{'protein_A': 174, 'protein_B': 226}

In [52]:
dict_1.items()


dict_items([('protein_A', 174), ('protein_B', 226)])

In [54]:
dict_1['protein_c']=556
dict_1

{'protein_A': 174, 'protein_B': 226, 'protein_c': 556}

In [55]:
dict_1.keys()

dict_keys(['protein_A', 'protein_B', 'protein_c'])

### Check if keys exists in a Dictionary

In [57]:
if 'protein_A' in dict_1:
    print("Yes protein_A is in the Dictionary")

Yes protein_A is in the Dictionary


In [59]:
if 'protein_B' in dict_1:
    print("Yes protein_B is in the Dictionary")
else:
    print("No protein_B is not in the Dictionary")

Yes protein_B is in the Dictionary


In [60]:
if 'protein_D' in dict_1:
    print("Yes protein_D is in the Dictionary")
else:
    print("No protein_D is not in the Dictionary")

No protein_D is not in the Dictionary


### Exercise

 protein_A and Protein_B , 174 and 226 respectively.. suppose i want to subtract 100 from each, protein A will 74 and protein B will be 126.